//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPIGrupo7Kinect.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NPIGrupo7Kinect.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se denomina descubrimiento de América al acontecimiento histórico que comenzó, el 12 de octubre de 1492, con la llegada a América de una expedición capitaneada por Cristóbal Colón por mandato de los reyes Isabel y Fernando de Castilla, la cual había partido del Puerto de Palos dos meses y nueve días antes y que, tras cruzar el océano Atlántico, llegó a una isla del continente americano, Guanahaní, a lo que creía que era la India. Este acontecimiento constituye uno de los momentos fundamentales de la histori [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string descubrimiento {
            get {
                return ResourceManager.GetString("descubrimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El domingo 3 de marzo de 1996 se celebraron elecciones generales en España. El presidente del Gobierno, el socialista Felipe González, se vio obligado a convocar elecciones cuando aún no habían pasado tres años de las anteriores, después de que su socio de gobierno Convergencia i Unió rompiera el pacto de legislatura y fuese imposible aprobar los presupuestos de aquel año. De hecho, las elecciones estaban originalmente previstas para el domingo 6 de julio de 1997, adelantándose 70 semanas.
        ///
        ///La de 1996 fue [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string elecciones {
            get {
                return ResourceManager.GetString("elecciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Guerra Civil Española, o Guerra de España,3​4​5​6​ fue un conflicto social, político y bélico —que más tarde repercutiría también en una crisis económica— que se desencadenó en España tras el fracaso parcial del golpe de Estado del 17 y 18 de julio de 1936 llevado a cabo por una parte del Ejército contra el gobierno de la Segunda República. Tras el bloqueo del Estrecho y el posterior puente aéreo que, gracias a la rápida colaboración de la Alemania nazi y la Italia fascista, trasladó las tropas rebeldes  [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string guerra {
            get {
                return ResourceManager.GetString("guerra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los expertos del Instituto Nacional de Meteorología sabían que en diciembre cayó mucha agua en Andalucía, pero no esperaban lo que ellos llaman una efeméride, un récord de precipitaciones. Sólo hasta la primera semana de enero, cuando han llegado los datos de los observatorios provinciales, pudieron afirmar que nunca el suelo andaluz recibió tanta en ese mes. Al menos, en lo concerniente a la Andalucía occidental y desde finales del siglo XIX, época desde la que se dispone de datos fiables.Incluso en las pr [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string lluvioso {
            get {
                return ResourceManager.GetString("lluvioso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Federico García Lorca (Fuente Vaqueros,1​ Granada, 5 de junio de 1898-camino de Víznar a Alfacar, Granada, 18 de agosto de 1936)2​ fue un poeta, dramaturgo y prosista español, también conocido por su destreza en muchas otras artes. Adscrito a la llamada Generación del 27, fue el poeta de mayor influencia y popularidad de la literatura española del siglo xx. Como dramaturgo se le considera una de las cimas del teatro español del siglo xx, junto con Valle-Inclán y Buero Vallejo. Murió fusilado tras el golpe d [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string lorca {
            get {
                return ResourceManager.GetString("lorca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En 1973, un equipo de arqueólogos descubre en el oasis egipcio de Kiffa las ruinas de una iglesia copta. Durante las excavaciones se desentierra la biblioteca del convento y en ella se localizan casi un centenar de manuscritos escritos en árabe, griego y latín. Uno de estos manuscritos, el libro de la luz en las sombras, data del siglo XII y puede ser la obra inédita del Avempace. El azar quiere que entre los paleógrafos encargados de estudiar los pergaminos se encuentren el español Julián Mestre y la docto [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string opalo {
            get {
                return ResourceManager.GetString("opalo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Guerra de Granada fue el conjunto de campañas militares que tuvieron lugar entre 1482 y 1491, emprendidas por la reina Isabel I de Castilla y su esposo el rey Fernando II de Aragón en el interior del reino nazarí de Granada, que culminaron con la Capitulaciones de Granada del rey Boabdil, quien había oscilado entre la alianza, el doble juego, la contemporización y el enfrentamiento abierto con ambos bandos y que tuvo como consecuencias la integración en la Corona de Castilla del último reino musulmán de  [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string tomaGranada {
            get {
                return ResourceManager.GetString("tomaGranada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;grammar version=&quot;1.0&quot; xml:lang=&quot;es-ES&quot; root=&quot;rootRule&quot; tag-format=&quot;semantics-ms/1.0&quot; xmlns=&quot;http://www.w3.org/2001/06/grammar&quot;&gt;
        ///  &lt;rule id=&quot;rootRule&quot;&gt;
        ///    &lt;one-of&gt;
        ///      &lt;item&gt;
        ///        &lt;tag&gt;$=&quot;AMPLIAR&quot;;&lt;/tag&gt;
        ///        &lt;one-of&gt;
        ///          &lt;item&gt; Zum &lt;/item&gt;
        ///          &lt;item&gt; Hacer Zum &lt;/item&gt;
        ///          &lt;item&gt; Aumentar &lt;/item&gt;
        ///          &lt;item&gt; Ampliar &lt;/item&gt;
        ///          &lt;item&gt; Mas cerca &lt;/item&gt;
        ///        &lt;/one-of&gt;
        ///      &lt;/item&gt;
        ///      &lt;item&gt;
        ///        &lt;tag&gt;$=&quot;REDUCIR&quot;;&lt;/tag&gt;
        ///        &lt;one-of&gt;
        ///          [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string XMLSpeech {
            get {
                return ResourceManager.GetString("XMLSpeech", resourceCulture);
            }
        }
    }
}
