/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import napakalakiGame.Monster;

/**
 *
 * @author xkuzz
 */
public class MonsterView extends javax.swing.JPanel {
  private Monster monsterModel; 

  /**
   * Creates new form MonsterView
   */
  public MonsterView() {
    initComponents();
  }
  
  public void setMonster(Monster m){
    monsterModel = m;
    monstruo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIMonsters/" +
                                          m.getName()+".jpg")));
    repaint();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    monstruo = new javax.swing.JLabel();

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(monstruo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(monstruo, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel monstruo;
  // End of variables declaration//GEN-END:variables
}
