/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.border.LineBorder;
import napakalakiGame.Treasure;

/**
 *
 * @author xkuzz
 */
public class TreasureView extends javax.swing.JPanel {
  private Treasure treasureModel;
  private boolean selected = false;
  /**
   * Creates new form TreasureView
   */
  public TreasureView() {
    initComponents();
  }
  
  public void setTreasure(Treasure t) {
    treasureModel = t;
    tesoro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUITreasures/" +
                                          t.getName()+".jpg")));
    repaint();
  }
  
  public boolean isSelected(){
    return selected;
  }
  
  public Treasure getTreasure(){
    return treasureModel;
  }
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    tesoro = new javax.swing.JLabel();

    addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        formMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(tesoro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(tesoro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    selected = !selected;
    if (selected) 
      setBorder(new LineBorder(Color.yellow));
    else 
      setBorder(null);
    repaint(); 
  }//GEN-LAST:event_formMouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel tesoro;
  // End of variables declaration//GEN-END:variables
}
